commutity/urls.py
from django.conf.urls import url
from . import views

app_name = 'commutity'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^login/$', views.LoginView.as_view(), name='login'),
        url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
        url(r'^create-account/$', views.CreateAccountView.as_view(), name='create-account')
    ]

djdashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^flick/', include('flick.urls')),
    url(r'^pazaak/', include('pazaak.urls')),
    url(r'^scrabble/', include('scrabble.urls'))
]

flick/urls.py
from django.conf.urls import url
from . import views

app_name = 'flick'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^login/$', views.LoginView.as_view(), name='login'),
        url(r'^create-acccount/$', views.CreateAccountView.as_view(), name='create-account'),
        url(r'^light-controller/$', views.LightControllerView.as_view(), name='light-controller'),
    ]

commutity/models.py
from django.db import models
from .utilities import tools

class User(models.Model):
    class Meta:
        db_table = 'Users'

    username = models.CharField(max_length=20, unique=True, db_index=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=10)

    def __str__(self) -> str:
        return tools.generic_obj_str(self, 'username', 'first_name', 'last_name', 'phone')


class Credentials(models.Model):
    class Meta:
        db_table = 'Credentials'

    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username')
    password = models.BinaryField(max_length=128)
    key = models.CharField(max_length=16)
    iv = models.BinaryField(max_length=128)
    
    def __str__(self) -> str:
        return '{0}(username={1}, password={2}, key={3}, iv={4})'.format(type(self).__name__, self.user.username, self.password, self.key, self.iv)

commutity/views.py
import logging
import django.core.exceptions
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect, render
from django.views import generic
from . import helper, models
from .authentication import info
from .authentication.encryption import PasswordEncryptor


logger = logging.getLogger(__name__)
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
logger.addHandler(console_handler)

ERROR_CTX = 'error'


class IndexView(generic.TemplateView):
    template_name = 'commutity/index.html'


class LoginView(generic.TemplateView):
    template_name = 'commutity/login.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page load """
        assert request.method == 'GET', 'expected GET request; received {0}'.format(request.method)
        return super().get(request)

    def post(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page submit """
        assert request.method == 'POST', 'expected POST request; received {0}'.format(request.method)
        print(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        context = {}
        if self._verify_user(username, password):
            # valid - login, redirect home
            request.session['user'] = helper.get_user(username)
            request.session['info'] = info.LoginInfo(username)
            logger.info('{0}'.format(request.session['info']))
            context['username'] = username
            return render(request, template_name=IndexView.template_name, context=context)
        else:
            context.clear()
            context[ERROR_CTX] = 'invalid username "{0}"'.format(username)
        return render(request, template_name=self.template_name, context=context)
        

    @staticmethod
    def _verify_user(username: str, password: str) -> bool:
        credentials = helper.get_credentials(username)
        manager = PasswordEncryptor(key=credentials.key, iv=credentials.iv)
        return manager.encrypt(password) == credentials.password


class LogoutView(generic.TemplateView):
    template_name = 'commutity/logout.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        print('get logout')
        if 'user' in request.session:
            user = request.session['user']
            info = request.session['info']
            info.log_out()
            logger.info('{0}'.format(info))
            del request.session['user']
        else:
#             raise Http404('user not recorded in session')
            return redirect('commutity:index')
        return render(request, template_name=self.template_name)
    
    
class CreateAccountView(generic.TemplateView):
    template_name = 'commutity/create-account.html'
    
    def get(self, request: HttpRequest) -> HttpResponse:
        return super().get(request)
    
    def post(self, request: HttpRequest) -> HttpResponse:
        print(request.POST)
        received = set(request.POST)
        print(received)
        expected = ('first_name',
                    'last_name',
                    'email',
                    'phone',
                    'username',
                    'password')
        if not all(field in received for field in expected):
            raise Http404('invalid fields')
        
        user = self._make_user(request.POST)
        credentials = self._make_credentials(user, request.POST['password'])
    
        user.save()
        credentials.save()
        
        return render(request, template_name=self.template_name)
    
    @staticmethod
    def _make_user(response: {str: str}) -> models.User:
        username = response['username']
        first_name = response['first_name']
        last_name = response['last_name']
        email = response['email']
        phone = response['phone']
        return models.User(username=username, first_name=first_name, last_name=last_name, phone=phone)
    
    @staticmethod
    def _make_credentials(user: models.User, password: str) -> models.Credentials:
        manager = PasswordEncryptor()
        encrypted = manager.encrypt(password)
        return models.Credentials(user=user, password=encrypted, key=manager.key, iv=manager.iv)

commutity/templates/commutity/base.html
<!DOCTYPE html>
<html lang="en">

	{% load static %}
	<head>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static "commutity/css/common.css" %}">

		{% block head %}
			<title>Commutity</title>
		{% endblock %}
	</head>

	<header>
		<div id="login-header">
			{% if request.session.user %}
				<p>{{ request.session.user.first_name }} {{ request.session.user.last_name }}</p>
			{% endif %}
			{% block login-header %}{% endblock %}
		</div>

		<div role="banner" class="header-banner">
			<div class="vertical-align" id="header-banner-title-text">
				<h1>commutity</h1>
			</div>
		</div>
		
		<div id="nav-bar">
			<ul class="no-bullets" id="nav-bar-list">
				<li class="nav-bar-horizontal nav-bar-active" id="nav-bar-home"><a href="{% url 'commutity:index' %}">Home</a></li>
				<li class="nav-bar-horizontal" id="nav-bar-get-started"><a href="{% url 'commutity:login' %}">Get Started</a></li>
				<li class="nav-bar-horizontal" id="nav-bar-about"><a>About</a></li>
				{% if request.session.user %}
					<li class="nav-bar-horizontal" id="nav-bar-logout"><a href="{% url 'commutity:logout' %}">Log Out</a></li>
				{% endif %}
			</ul>
		</div>

		<script type="text/javascript">
			function switchActiveNavBarPerspective(elementPrevious, elementCurrent) {
				$(elementPrevious).removeClass("nav-bar-active");
				$(elementCurrent).addClass("nav-bar-active");
			}

			function makeNavButtonActive(element) {
				var navButtons = $("#nav-bar-list li");
				navButtons.each(function(index, li){ $(li).removeClass("nav-bar-active"); });
				$(element).addClass("nav-bar-active");
			}

			function initNavBar() {
				$("#nav-bar-list li").each(function(index, li){ $(li).click(function(){ makeNavButtonActive(li); }) });
			}

			function fieldEmpty(element) {
				return $(element).val().length === 0;
			}

			$(document).ready(function() {
				initNavBar();
				makeNavButtonActive("#nav-bar-home");
			});
		</script>
	</header>

	<body>
		{% block body %}{% endblock %}
	</body>

	<footer>
	</footer>
</html>

commutity/templates/commutity/create-account.html
<!DOCTYPE html>

{% extends "commutity/base.html" %}
{% load static %}

<html lang="en">
	{% block head %}
		<title>Commutity - Create Account</title>

		<link rel="stylesheet" type="text/css" href="{% static "commutity/css/create-account.css" %}">
	{% endblock %}

	{% block body %}
		<div class="form-container" id="create-body">
			<h2>Create an Account</h2>

			<form action="{% url 'commutity:create-account' %}" method="post">
				{% csrf_token %}

				<h3>Tell us about yourself.</h3>

				<div class="input-container">
					<label class="input-text-box-label" for="first-name-box">First Name</label>
					<input type="text" name="first_name" class="input-text-box" id="first-name-box"/>

					<label class="input-text-box-label" for="last-name-box">Last Name</label>
					<input type="text" name="last_name" class="input-text-box" id="last-name-box"/>

					<label class="input-text-box-label" for="email-box">Email Address</label>
					<input type="text" name="email" class="input-text-box" id="email-address-box"/>

					<label class="input-text-box-label" for="phone-box">Phone Number</label>
					<input type="text" name="phone" class="input-text-box" id="phone-number-box"/>

					<label class="input-text-box-label" for="username-box">Username</label>
					<input type="text" name="username" class="input-text-box" id="username-box"/>

					<label class="input-text-box-label" for="password-box">Password</label>
					<input type="password" name="password" class="input-text-box" id="password-box"/>
				</div>

				<button type="submit" class="btn btn-success btn-md disabled" id="btn-create">Create</button>
			</form>
		</div>

		<script type="text/javascript">

			$(document).ready(function(){
			});
		</script>
	{% endblock %}

</html>

commutity/templates/commutity/index.html
<!DOCTYPE html>

{% extends "commutity/base.html" %}

<html lang="en">

	{% block body %}
		<p>Hello, boo!</p>
	{% endblock %}

</html>

commutity/templates/commutity/login.html
<!DOCTYPE html>

{% extends "commutity/base.html" %}
{% load static %}

<html lang="en">
	{% block head %}
		<title>Commutity - Login</title>

		<link rel="stylesheet" type="text/css" href="{% static "commutity/css/login.css" %}">
	{% endblock %}

	{% block body %}
		<div id="login-body">
			<h2>Login</h2>

			<form action="{% url 'commutity:login' %}" method="post">
				{% csrf_token %}
				<label class="login-box-label" for="login-username-box">Username</label>
				<input type="text" name="username" class="login-text-box" id="login-username-box"/>

				<label class="login-box-label" for="login-password-box">Password</label>
				<input type="password" name="password" class="login-text-box" id="login-password-box"/>

				<button type="submit" class="btn btn-success btn-md disabled" id="btn-login">Go</button>
			</form>

			<div id="create-user-body">
				<p>Don't have an account yet? <a href="{% url 'commutity:create-account' %}">Make one.</a></p>
			</div>
		</div>

		<script type="text/javascript">
			/* Adds a red, bolded border around inputElement's textbox if the field is empty */
			function _validateLoginInput(inputElement) {
				if (fieldEmpty(inputElement))
				{
					$(inputElement).addClass("text-box-invalid");
				}
				else
				{
					$(inputElement).removeClass("text-box-invalid");
				}
			}

			/* Disables $(buttonElement) if either of the input fields are not yet populated */
			function _validateLoginButton(buttonElement) {
				var invalidInput = fieldEmpty("#login-username-box") || fieldEmpty("#login-password-box");
				$(buttonElement).prop("disabled", invalidInput);
				if (invalidInput) {
					$(buttonElement).addClass("disabled");
				}
				else {
					$(buttonElement).removeClass("disabled");
				}
			}

			function _validateLoginElements(inputElement) {
				_validateLoginInput(inputElement);
				_validateLoginButton("#btn-login");
			}

			$(document).ready(function(){
				$("#btn-login").prop("disabled", true);
				$("#login-username-box").keyup(function(){ _validateLoginElements("#login-username-box"); });
				$("#login-password-box").keyup(function(){ _validateLoginElements("#login-password-box"); });
				makeNavButtonActive("#nav-bar-get-started");
			});
		</script>
	{% endblock %}

</html>

commutity/templates/commutity/logout.html
<!DOCTYPE html>

{% extends "commutity/base.html" %}
{% load static %}

<html lang="en">
	{% block login-header %}
		<p>You have been successfully logged out.</p>
	{% endblock %}
</html>