djdashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^flick/', include('flick.urls')),
    url(r'^pazaak/', include('pazaak.urls')),
    url(r'^scrabble/', include('scrabble.urls'))
]

flick/urls.py
from django.conf.urls import url
from . import views

app_name = 'flick'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^login/$', views.LoginView.as_view(), name='login'),
        url(r'^create-acccount/$', views.CreateAccountView.as_view(), name='create-account'),
        url(r'^light-controller/$', views.LightControllerView.as_view(), name='light-controller'),
    ]

flick/lights/controller.py
import json
import urllib.parse
import urllib.request
from django.utils.decorators import method_decorator


class verify_success:
    """
    Function decorator to verify that the Hue API response is successful.

    Expected successful response is something like:
    [{'success': {'/lights/6/state/on': False}}]

    If success is not found, raises ValueError.
    Proceeds to return the original result of the decorated function.

    When decorating a method, use in conjunction with Django's method_decorator.
    """
    def __init__(self, function: callable):
        self._f = function

    def __call__(self, *args, **kwargs):
        response = self._f(*args, **kwargs)
        if not any('success' in entry for entry in response):
            raise ValueError('failed to receive success status message; received: \n{0}'.format(response))
        return response


class LightController:
    """
    Class containing methods to interact with the Philips Hue bridge via API calls.
    """

    def __init__(self, bridge_ip_address: str, hue_api_key: str):
        self._bridge_ip_address = bridge_ip_address
        self._api_key = hue_api_key


    def _form_api_call(self, command: str) -> str:
        """
        Returns a string of the URL required to make an API call.

        Example:
        To get all lights, the argument would be 'lights', returning:
        'http://{BRIDGE.IP.ADDRESS}/api/{API-USERNAME}/lights'
        """
        return 'http://{0}/api/{1}/{2}'.format(self._bridge_ip_address, self._api_key, command)


    def get(self, command: str) -> dict:
        """
        Issues an HTTP GET request using command.
        Command should be a Hue API command only - the URL will be automatically built by the method.
        Deserializes the response and returns a dictionary containing the result.
        """
        url = self._form_api_call(command)
        with urllib.request.urlopen(url) as response:
            content = response.read()
            content = content.decode(encoding='utf-8')
            return json.loads(content)


    @method_decorator(verify_success)
    def toggle(self, light_number: int, light_data: dict) -> [dict]:
        """
        Toggles the given light on/off.
        light_number is an real integer corresponding to the light, as returned by the Hue API.
        light_data is the corresponding serialized JSON dictionary for that light.

        Toggling lights via the API expects an HTTP PUT request.
        Returns the response from the API as a serialized JSON object.

        Successful response should be something like:
        [{'success': {'/lights/6/state/on': False}}]
        """
        is_light_on = light_data['state']['on']
        parameters = {'on': not is_light_on}
        payload = json.dumps(parameters)
        payload = bytes(payload, encoding='utf-8')
        url = 'http://{0}/api/{1}/lights/{2}/state'.format(self._bridge_ip_address, self._api_key, light_number)
        request = urllib.request.Request(url)
        request.get_method = lambda: 'PUT'

        with urllib.request.urlopen(request, data=payload) as response:
            content = response.read()
            content = content.decode(encoding='utf-8')
            return json.loads(content)


    def lights(self) -> [dict]:
        """
        Returns a list of all discovered lights, where each "light" is represented by its dictionary JSON response.
        """
        response = self.get('lights')
        result = []
        for number, info in response.items():
            info['number'] = int(number)
            result.append(info)
        return result

flick/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

import json
import logging
import urllib.error

from .lights.controller import LightController
from .security import setup


logger = logging.getLogger(__name__)
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
logger.addHandler(console_handler)

# flick#web admin
bridge_ip_address, admin_username = setup.authenticate()

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'flick/index.html'


class LoginView(generic.TemplateView):
    template_name = 'flick/login.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page load """
        assert request.method == 'GET', 'expected GET request; received {0}'.format(request.method)
        return super().get(request)

    def post(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page submit """
        assert request.method == 'POST', 'expected POST request; received {0}'.format(request.method)
        return render(request, template_name=self.template_name, context=context)


class CreateAccountView(generic.TemplateView):
    template_name = 'flick/create-account.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page load """
        assert request.method == 'GET', 'expected GET request; received {0}'.format(request.method)
        return super().get(request)

    def post(self, request: HttpRequest) -> HttpResponse:
        """ Invoked on page submit """
        assert request.method == 'POST', 'expected POST request; received {0}'.format(request.method)
        return render(request, template_name=self.template_name, context=context)


class LightControllerView(generic.TemplateView):
    template_name = 'flick/light-controller.html'
    controller = LightController(bridge_ip_address, admin_username)
    lights = {}

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request: HttpRequest) -> HttpResponse:
        print('get')
        lights = []

        try:
            lights = self.refresh_lights()
        except urllib.error.URLError as e:
            e.reason = 'check bridge_ip_address and admin_username global variables in views.py'
            logger.error(e.reason)
            raise

        context = {'lights': lights, 'lights_json': json.dumps(lights)}
        return render(request, template_name=self.template_name, context=context)


    def post(self, request: HttpRequest) -> HttpResponse:
        print('post')
        print(request.POST)
        context = self.process_post(request.POST)
        return render(request, template_name=self.template_name, context=context)


    def process_post(self, data: dict) -> dict:
        """
        Processes the HTTP POST data received from the site.
        Returns a context dictionary to be passed back to the site (empty if no data).

        Expected commands:
        -----------------
        TOGGLE
        REFRESH
        """
        context = {}

        if 'command' not in data:
            raise KeyError('failed to receive "command" from AJAX response')
        command = data['command'].upper()
        logger.debug(command)

        if command == 'TOGGLE':
            self.toggle_light(data)
            light_number = self._verify_light_number(data['number'])
            context['toggled_light_number'] = json.dumps(light_number)
        elif command == 'REFRESH':
            pass

        lights = self.refresh_lights()
        context['lights'] = lights
        context['lights_json'] = json.dumps(lights)

        return context


    def toggle_light(self, data: dict):
        """
        Toggles the given light represented by 'data'.
        If it's on, turns it off, and vice versa.

        'data' is a JSON-serialized dictionary representing one light,
        received from the AJAX request triggered when toggling a light on/off.
        """
        light_number = self._verify_light_number(data['number'])
        light_data = self.lights[light_number]
        self.controller.toggle(light_number, light_data)


    @staticmethod
    def _verify_light_number(number_from_data: str) -> str:
        """
        Verifies that number_from_data is an integer.
        Returns the number as an `int` object.

        number_from_data is the value associated with the key 'number' from the AJAX response when toggling a light,
        e.g., data['number'].

        Example:
        '1' -> 1

        Raises ValueError if number_from_data is not a string representation of an integer.
        """
        number_from_data = number_from_data.strip()
        if not number_from_data.isdigit():
            raise ValueError(
                'expected to receive an integer unique light number; instead received "{0}"'.format(number_from_data))
        return int(number_from_data)


    @classmethod
    def refresh_lights(cls) -> [dict]:
        """
        Updates cls.lights with refreshed information.
        Stores lights in a dictionary with a single light's uniqueid as each key,
        and serialized JSON dictionary of that light as each value.
        """
        cls.lights = {light['number']: light for light in cls.controller.lights()}
        lights = []
        for light in cls.lights.values():
            info = {k: light[k] for k in ('name', 'number')}
            info['on'] = light['state']['on']
            lights.append(info)

        return sorted(lights, key=lambda d: d['name'])

flick/templates/flick/base.html
<!DOCTYPE html>

<html lang="en">
    {% load static %}
	<head>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static "flick/css/common.css" %}">

		{% block head %}
		<title>Flick</title>
		{% endblock %}
	</head>

	<header>
        <div id="app-name" class="heading">Flick</div>

        <div id="nav-bar">
			<ul class="no-bullets" id="nav-bar-list">
				<li class="nav-bar-horizontal nav-bar-active" id="nav-bar-home"><a href="{% url 'flick:index' %}">Home</a></li>
				<li class="nav-bar-horizontal" id="nav-bar-about"><a>About</a></li>
				<li class="nav-bar-horizontal" id="nav-bar-get-started"><a href="{% url 'flick:login' %}">Get Started</a></li>
                <li class="nav-bar-horizontal" id="nav-bar-lights"><a href="{% url 'flick:light-controller' %}">Lights</a></li>
			</ul>
		</div>

        {% block header %}
        {% endblock %}
	</header>


	<body>
		{% block body %}
        {% endblock %}
        <script type="text/javascript">
			function switchActiveNavBarPerspective(elementPrevious, elementCurrent) {
				$(elementPrevious).removeClass("nav-bar-active");
				$(elementCurrent).addClass("nav-bar-active");
			}

			function makeNavButtonActive(element) {
				var navButtons = $("#nav-bar-list li");
				navButtons.each(function(index, li){ $(li).removeClass("nav-bar-active"); });
				$(element).addClass("nav-bar-active");
			}

			function initNavBar() {
				$("#nav-bar-list li").each(function(index, li){ $(li).click(function(){ makeNavButtonActive(li); }) });
			}

			$(document).ready(function() {
				initNavBar();
				//makeNavButtonActive("#nav-bar-home");
			});
		</script>

		{% block script %}
		{% endblock %}
	</body>

	<footer>
	</footer>
</html>

flick/templates/flick/create-account.html
<!DOCTYPE html>

{% extends "flick/base.html" %}
{% load static %}

<html lang="en">
	{% block head %}
		<title>Flick - Create Account</title>
		<link rel="stylesheet" type="text/css" href="{% static "flick/css/create-account.css" %}">
		<script type="text/javascript" src="{% static 'flick/js/common.js' %}"></script>
	{% endblock %}

	{% block body %}
		<div class="form-container" id="create-body">
			<h2>Create an Account</h2>

			<form action="{% url 'flick:create-account' %}" method="post" id="create-account-form">
				{% csrf_token %}

				<div class="input-container">
					<label class="input-text-box-label" for="first-name-box">First Name</label>
					<input type="text" name="first_name" class="input-text-box" id="first-name-box"/>

					<label class="input-text-box-label" for="last-name-box">Last Name</label>
					<input type="text" name="last_name" class="input-text-box" id="last-name-box"/>

					<label class="input-text-box-label" for="email-box">Email Address</label>
					<input type="text" name="email" class="input-text-box" id="email-address-box"/>

					<label class="input-text-box-label" for="username-box">Username</label>
					<input type="text" name="username" class="input-text-box" id="username-box"/>

					<label class="input-text-box-label" for="password-box">Password</label>
					<input type="password" name="password" class="input-text-box" id="password-box"/>
				</div>

				<button type="submit" class="btn btn-success btn-md disabled" id="btn-create">Create</button>
			</form>
		</div>
	{% endblock %}

	{% block script %}
		<script type="text/javascript">
			$(document).ready(function(){
				makeNavButtonActive('#nav-bar-get-started');
				common.requireFieldNonEmpty("#first-name-box");
				common.requireFieldNonEmpty("#last-name-box");
				common.requireFieldNonEmpty("#email-address-box");
				common.requireFieldNonEmpty("#username-box");
				common.requireFieldNonEmpty("#password-box");
				common.disableButtonUnlessAllFieldsFilled("#btn-create", "form#create-account-form :input");
			});
		</script>
	{% endblock %}
</html>

flick/templates/flick/index.html
<!DOCTYPE html>

{% extends "flick/base.html" %}
{% load static %}

<html lang="en">

    {% block header %}

    {% endblock %}

	{% block body %}
    <div class="background-container">
        <!-- image  source: https://www.youtube.com/watch?v=pOUqL5jGbn0 -->
        <img class="background-image" src="{% static "flick/images/rainbow_lights_background.jpg" %}">
	</div>
	{% endblock %}

</html>

flick/templates/flick/light-controller.html
<!DOCTYPE html>

{% extends "flick/base.html" %}
{% load static %}

<html lang="en">

    {% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'flick/css/light-controller.css' %}">
    {% endblock %}

	{% block body %}
    <div id="lights-container">
        <div id="header-button-container" class="header-button">
            <button type="button" class="btn btn-info" id="btn-refresh" data-url="{% url 'flick:light-controller' %}"><i id="btn-refresh-span" class="fas fa-sync"></i> Refresh</button>
        </div>
        <ul class="no-bullets" id="lights-list">
            {% for light in lights %}
            <div id="light-container-{{ forloop.counter }}">
                <button type="button" class="btn btn-default" data-url="{% url 'flick:light-controller' %}" data-number="{{ light.number }}"><i id="btn-light-span-{{ light.number }}" class="fas fa-2x"></i></button>
                <li class="same-line" id="light-{{ light.uniqueid }}" data-url="{% url 'flick:light-controller' %}">{{ light.name }}</li>
            </div>
            {% endfor %}
        </ul>
    </div>
	{% endblock %}

    {% block script %}
    <script type="text/javascript">
        function _revertRefreshButton() {
            $("#btn-refresh").toggleClass("btn-success btn-info");
            $("#btn-refresh-span").toggleClass("fa-check fa-sync");
        }

        function _confirmRefreshButton() {
            $("#btn-refresh").toggleClass("btn-info btn-success");
            $("#btn-refresh-span").removeClass("fa-spin");
            $("#btn-refresh-span").toggleClass("fa-check fa-sync")
        }

        /*
         * Temporarily (for half a second) turns the refresh button green (bootstrap class "btn-success"),
         * and the icon to a checkmark (font-awesome class "fa-check").
         * Reverts after 2 seconds.
         * Refreshes the light toggles with initLightButtons().
         */
        function refreshButtonSuccess() {
            setTimeout(_confirmRefreshButton, 500);
            setTimeout(_revertRefreshButton, 2000);
            initLightButtons();
        }

        /*
         * Prepares the refresh button's functionality.
         * When clicked, sends a POST request as:
         *   {'command': 'refresh'}
         * The refresh icon begins spinning to indicate progress.
         * Upon success, temporarily provides a visual indication on the refresh button to indicate completion.
         * Refreshes the light toggles with initLightButtons().
         */
        function bindRefreshButton() {
            $("#btn-refresh").click(function(e) {
                e.preventDefault();
                $("#btn-refresh-span").addClass("fa-spin");
                $.ajax({
                    type: "POST",
                    url: $(this).data("url"),
                    data: {
                        command: "refresh"
                    },
                    success: refreshButtonSuccess
                });
            });
        }

        /*
         * Prepares each light's toggle-button functionality.
         * Clicking the toggle sends POST request as {'command': 'toggle', 'number': <light-number>}.
         * Upon success, updates the toggle to reflect the light's new state.
         */
        function bindLightButtons() {
            $("#lights-list button").each(function(index, button) {
                $(button).click(function(e) {
                    e.preventDefault();
                    $.ajax({
                        type: "POST",
                        url: $(this).data("url"),
                        data: {
                            command: "toggle",
                            number: $(this).data("number")
                        },
                        /*
                        success: function() {
                            var toggledLightNumber = JSON.parse("{{ toggled_light_number|escapejs }}");
                            alert(toggledLightNumber);
                            var spanHtmlID = "#btn-light-span" + toggledLightNumber;
                            $(spanHtmlID).toggleClass("fa-toggle-off fa-toggle-on");
                        }
                        */
                        success: function(){ $(button).children("i").toggleClass("fa-toggle-on fa-toggle-off"); }
                    });
                })
            });
        }

        /*
         * Parses the contextual template variable 'lights_json' received from LightControllerView.
         * lights_json is a list of dictionaries, with keys 'name', 'number', and 'on' corresponding to each light.
         * Lights that have 'on'=True will get an "on" toggle,
         * and those that are 'off' get an "off" toggle.
         */
        function initLightButtons() {
            var lights = JSON.parse("{{ lights_json|escapejs }}");
            for (var i = 0; i < lights.length; ++i) {
                var light = lights[i];
                var spanHtmlID = "#btn-light-span-" + light["number"];
                if (light["on"]) {
                    $(spanHtmlID).removeClass("fa-toggle-off");
                    $(spanHtmlID).addClass("fa-toggle-on");
                }
                else {
                    $(spanHtmlID).removeClass("fa-toggle-on");
                    $(spanHtmlID).addClass("fa-toggle-off");
                }
            }
        }

        $(document).ready(function(){
            makeNavButtonActive("#nav-bar-lights");
            initLightButtons();
            bindRefreshButton();
            bindLightButtons();
        });
    </script>
	{% endblock %}

</html>

flick/templates/flick/login.html
<!DOCTYPE html>

{% extends "flick/base.html" %}
{% load static %}

<html lang="en">
	{% block head %}
		<script type="text/javascript" src="{% static 'flick/js/common.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'flick/css/login.css' %}">
		<title>Flick - Login</title>
	{% endblock %}

	{% block header %}
		<script type="text/javascript">
			$(document).ready(function() {
				$("#btn-login").prop("disabled", true);
			});
		</script>
	{% endblock %}

	{% block body %}
		<div id="login-body">
			<h2>Login</h2>

			<form action="{% url 'flick:login' %}" method="post" id="login-form">
				{% csrf_token %}
				<label class="login-box-label" for="login-username-box">Username</label>
				<input type="text" name="username" class="login-text-box" id="login-username-box"/>

				<label class="login-box-label" for="login-password-box">Password</label>
				<input type="password" name="password" class="login-text-box" id="login-password-box"/>

				<button type="submit" class="btn btn-success btn-md disabled" id="btn-login">Go</button>
			</form>

			<div id="create-user-body">
				<p>Don't have an account yet? <a href="{% url 'flick:create-account' %}">Make one.</a></p>
			</div>
		</div>
	{% endblock %}

	{% block script %}
		<script type="text/javascript">
			$(document).ready(function(){
				makeNavButtonActive("#nav-bar-get-started");
				common.requireFieldNonEmpty("#login-username-box");
				common.requireFieldNonEmpty("#login-password-box");
				common.disableButtonUnlessAllFieldsFilled("#btn-login", "form#login-form :input");
			});
		</script>
	{% endblock %}

</html>